version: '3'

services:
   transpiler:
      image: node:8.9.0-alpine
      container_name: tsc
      working_dir: /app
      volumes:
         - .:/app            # share your code with the containers
         - node_modules:/app/node_modules
         - dist:/app/dist
      # typescript should watch the src directory
      entrypoint: sh
      command: -c "npm i -g typescript; npm i; npm run compile"

   server:
      image: node:8.9.0-alpine
      container_name: server
      expose:
         - 1337
      volumes:
         - .:/app            # share your code with the containers
         - dist:/app/dist
         - ./src/template:/app/template
      working_dir: /app
      links:
         - mongodb
      command: npm run server
      environment:
         USER: user1
         FORCE_COLOR: 1

   web1:
      image: node:8.9.0-alpine
      container_name: express-container1
      ports:
         - 3001:3000
      volumes:
         - .:/app            # share your code with the containers
         - dist:/app/dist
         - ./src/template:/app/template
      working_dir: /app
      links:
         - mongodb
      command: npm start
      depends_on:
         - server
      environment:
         USER: user1
         FORCE_COLOR: 1

   web2:
      image: node:8.9.0-alpine
      container_name: express-container2
      ports:
         - 3002:3000
      volumes:
         - .:/app            # share your code with the containers
         - dist:/app/dist
         - ./src/template:/app/template
      working_dir: /app
      depends_on:
         - server
      command: npm start
      environment:
         USER: user2
         FORCE_COLOR: 1

   web3:
      image: node:8.9.0-alpine
      container_name: express-container3
      ports:
         - 3003:3000
      volumes:
         - .:/app            # share your code with the containers
         - dist:/app/dist
         - ./src/template:/app/template
      working_dir: /app
      depends_on:
         - server
      command: npm start
      environment:
         USER: user3
         FORCE_COLOR: 1

   mongodb:
      image: mongo
      container_name: mongodb
      ports:
         - 27017:27017
      expose:
         - 27017

   mongo-express:
      image: mongo-express
      container_name: mongo-express
      links:
         - mongodb
      ports:
         - 7000:8081
      environment:
         - ME_CONFIG_MONGODB_SERVER=mongodb
         - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance

volumes:
   node_modules:
   dist:
